

{src/web2/wrap-cgi.i}
{lib/htmlib.i}
{lib/princexml.i}

output-content-type ("text/html":U).

def var   lc-account         as char.
def var   lc-status          as char.
def var   lc-assign          as char.
def var   lc-area            as char.  
def var   lc-user            as char.  
def var   lc-category        as char.  
def var   lc-pdf             as char.  


assign  lc-global-company =  "ouritdept"      
                     lc-account     =  "AllHDDataAvail"
                     lc-status      =  "allopen"        
                     lc-assign      =  "Ian Bibby"      
                     lc-area        =  "AllHDDataAvail"
                     lc-user        =  "DavidShilling"
                     lc-category    =  "AllHDDataAvail" .


   lc-pdf = "HELLO". 
  
 /* 
    RUN prince/issue.p ( lc-global-company,
                          lc-account,
                          lc-status,
                          lc-assign,
                          lc-area,
                          lc-user,
                          lc-category,
                          output lc-pdf ).
*/

   {&out}
     '<!-- Generated by Webspeed: http://www.webspeed.com/, http://www.possenet.org/ --><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"><html><body><h1> OK <br><br>' + lc-pdf + ' </h1/></body></html>'.
